### ISSUE TITLE
Documentation missing mandatory feilds 

### ISSUE THREAD

**Issue by DeanKamali** [nknapp/node-child-service#2]
Hi 

Thanks for spending the time to develop this wonderful library, I'm confused about which of the options are required and can use defaults.

**Comment by nknapp** [comment]
sorry for the long delay. I haven't spent much time on Github in December.

You are right. It is not clear from the docs which options are required. It should have been auto-generated though. 
Have a look at the typings (https://github.com/nknapp/node-child-service/blob/master/types/index.d.ts#L10) or the jsdoc-comments and it will become clear (https://github.com/nknapp/node-child-service/blob/master/src/index.js#L17)

I guess the jsdoc-comments are wrong. It should be `Regex=` instead of `Regex?`

**Comment by nknapp** [comment]
I fixed this in 2.4.1, hope it's not too late for you...

**Comment by DeanKamali** [comment]
No it’s not too late, would be great, I’m using it with an electron app, I have number of binaries I need to execute, I think your library is an excellent fit 😄
